## Binomial distribution

* It is widely used probability distribution of a discrete random variable. 
* Plays major role in quality control and quality assurance function. 

$P(X = x\mid n,\pi)$ = $\frac{n!}{x!(n - x)!}\pi^x (1 - \pi)^{n-x} $
* where P(X = x) is the probability of getting x successes in n trials
and $\pi$ is the probability of an event of interest

### Some important functions in Python for Binomial distribution:

#### 1) Probability mass function

##### scipy.stats.binom.pmf gives the probability mass function for the binomial distribution

binomial = scipy.stats.binom.pmf (k,n,p), 
* where k is an array and takes values in {0, 1,..., n}
* n and p are shape parameters for the binomial distribution

The output, binomial, gives probability of binomial distribution function in terms of array.

#### 2) Cumulative Density function

cumbinomial = scipy.stats.binom.cdf(k,n,p) gives cumulative binomial distribution.

The output, cumbinomial, gives cumulative probability of binomial distribution function in terms of array.

####  3)  Plot the binomial Density function

The function, matplotlib.pyplot.plot(k, binomial, ‘o-’) gives us plot of the binomial distribution function.

### Example 1

In [2]:
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

A LED bulb manufacturing company regularly conducts quality checks at specified periods on the products it manufactures.
Historically, the failure rate for LED light bulbs that the company manufactures is 5%. Suppose a random sample of 10 LED light bulbs is selected.
What is the probability that 
* a) None of the LED bulbs are defective?
* b) Exactly one of the LED bulbs is defective?
* c) Two or fewer of the LED bulbs are defective?
* d) Three or more of the LED bulbs are defective

In [3]:
# Write code here
r= np.arange(0,11)
p=stats.binom.pmf(r,10,0.95)

In [8]:
p

array([9.76562500e-14, 1.85546875e-11, 1.58642578e-09, 8.03789063e-08,
       2.67259863e-06, 6.09352488e-05, 9.64808106e-04, 1.04750594e-02,
       7.46347985e-02, 3.15124705e-01, 5.98736939e-01])

In [5]:
#  None of the LED bulbs are defective
p[10]

0.5987369392383787

In [6]:
# Exactly one of the LED bulbs is defective
p[1]

1.8554687500000156e-11

In [7]:
# Two or fewer of the LED bulbs are defective
p[0]+p[1]+p[2]

1.6050781250000114e-09

In [9]:
# Three or more of the LED bulbs are defective
1-(p[0]+p[1]+p[2])

0.9999999983949219

### EXERCISE

The percentage of orders filled correctly at Wendy's was approximately 86.8%. Suppose that you go to drive-through window at Wendy's and place an order. Two friends of yours independently place orders at the drive-through window at the same Wendy's.

What are the probabilities that 
* a) all three 
* b) none of the three
* c) atleast two of the three orders will be filled correctly?
* d) what is the mean and standard deviation of the orders filled correctly?

In [10]:
a=np.arange(0,4)
pr=stats.binom.pmf(a,3,0.868)
pr

array([0.00229997, 0.0453721 , 0.2983559 , 0.65397203])

In [12]:
# all three filled correctly
pr[3]

0.653972032

In [13]:
# none of the three filled correctly
pr[0]

0.002299968

In [14]:
# atleast two of the three orders will be filled correctly
pr[2]+pr[3]

0.9523279359999999

In [15]:
#  what is the mean and standard deviation of the orders filled correctly
import math
print("Mean",3*0.868)
print("Standard deviation", math.sqrt(3*0.868*0.132))

Mean 2.604
Standard deviation 0.5862832080146932


### EXERCISE

**You and your two friends go to Pizza Hut which recently filled approximately 88.3% of the orders correctly.
What is the probability of that.**

* a. all three orders will be filled correctly?
* b. none of orders will be filled correctly?
* c. at least two of three orders will be filled correctly?
* d. What are the mean and standard deviation of the orders filled correctly?

**Hint:** 
Mean and standard deviation of binomial distribution:
* $\mu     = n\pi$ 
* $\sigma  = \sqrt{n\pi(1-\pi)}$ 
where n is the size of the sample and $\pi$ is the probability of the event of interest

In [16]:
b=np.arange(0,4)
pr1=stats.binom.pmf(b,3,0.883)
pr1

array([0.00160161, 0.03626216, 0.27367084, 0.68846539])

In [17]:
# all three orders will be filled correctly
pr1[3]

0.688465387

In [18]:
# none of orders will be filled correctly
pr1[0]

0.0016016129999999991

In [19]:
# at least two of three orders will be filled correctly
pr1[2]+pr1[3]

0.9621362259999999

In [20]:
# What are the mean and standard deviation of the orders filled correctly
print("mean",3*0.883)
print("standard deviation",math.sqrt(3*0.883*0.117))

mean 2.649
standard deviation 0.556716265255471
